<?php

namespace Database\Seeders;

/**
 * Bank soal IPA untuk jenjang SMP kelas 7-9.
 */
class IpaQuestionSeeder extends QuestionBankSeeder
{
    protected function package(): array
    {
        return [
            'title' => 'Latihan Harian IPA',
            'slug' => 'latihan-harian-ipa',
            'subject' => 'IPA',
            'description' => 'Bank soal IPA SMP kelas 7-9: biologi, fisika, dan kimia dasar.',
            'duration_minutes' => 30,
            'questions_per_session' => 15,
        ];
    }

    protected function questions(): array
    {
        return [
            [
                'q' => 'Kemampuan berikut yang dimiliki makhluk hidup tetapi tidak dimiliki benda mati adalah ...',
                'options' => [
                    'A' => 'Bergerak dari satu tempat ke tempat lain',
                    'B' => 'Memerlukan energi untuk bekerja',
                    'C' => 'Berkembang biak menghasilkan keturunan',
                    'D' => 'Bertambah besar ukurannya',
                    'E' => 'Mengalami perubahan bentuk',
                ],
                'key' => 'C',
                'explanation' => "Mobil bisa bergerak, memerlukan energi, dan balon bisa bertambah besar, jadi ciri-ciri itu tidak khas makhluk hidup.\n\nYang tidak pernah dimiliki benda mati adalah berkembang biak (reproduksi), yaitu menghasilkan keturunan baru yang sejenis.",
            ],
            [
                'q' => 'Urutan tingkatan takson dari yang paling tinggi ke paling rendah adalah ...',
                'options' => [
                    'A' => 'Kingdom - Kelas - Filum - Ordo - Famili - Genus - Spesies',
                    'B' => 'Kingdom - Filum - Kelas - Ordo - Famili - Genus - Spesies',
                    'C' => 'Spesies - Genus - Famili - Ordo - Kelas - Filum - Kingdom',
                    'D' => 'Filum - Kingdom - Kelas - Famili - Ordo - Genus - Spesies',
                    'E' => 'Kingdom - Kelas - Ordo - Filum - Famili - Spesies - Genus',
                ],
                'key' => 'B',
                'explanation' => "Urutan takson dari tertinggi (anggota paling banyak) ke terendah (anggota paling sedikit):\nKingdom -> Filum/Divisi -> Kelas -> Ordo -> Famili -> Genus -> Spesies.\n\nSemakin ke bawah, semakin sedikit anggotanya tetapi semakin banyak persamaan cirinya.",
            ],
            [
                'q' => 'Bagian sel yang dimiliki sel tumbuhan tetapi tidak dimiliki sel hewan adalah ...',
                'options' => [
                    'A' => 'Inti sel dan sitoplasma',
                    'B' => 'Membran sel dan ribosom',
                    'C' => 'Dinding sel dan kloroplas',
                    'D' => 'Mitokondria dan lisosom',
                    'E' => 'Badan Golgi dan vakuola kecil',
                ],
                'key' => 'C',
                'explanation' => "Inti sel, sitoplasma, membran sel, ribosom, mitokondria, dan badan Golgi ada pada kedua jenis sel.\n\nCiri khas sel tumbuhan adalah dinding sel (dari selulosa, membuat sel kaku) dan kloroplas (tempat fotosintesis). Keduanya tidak ada pada sel hewan.",
            ],
            [
                'q' => 'Urutan tingkat organisasi kehidupan dari yang paling sederhana adalah ...',
                'options' => [
                    'A' => 'Jaringan - sel - organ - sistem organ - organisme',
                    'B' => 'Sel - organ - jaringan - sistem organ - organisme',
                    'C' => 'Sel - jaringan - organ - sistem organ - organisme',
                    'D' => 'Organ - jaringan - sel - organisme - sistem organ',
                    'E' => 'Sel - jaringan - sistem organ - organ - organisme',
                ],
                'key' => 'C',
                'explanation' => "Sel adalah unit terkecil kehidupan. Sel-sel sejenis berkumpul membentuk jaringan, beberapa jaringan membentuk organ, beberapa organ yang bekerja sama membentuk sistem organ, dan seluruh sistem organ menyusun organisme.\n\nJadi urutannya: sel -> jaringan -> organ -> sistem organ -> organisme.",
            ],
            [
                'q' => 'Peristiwa berikut yang termasuk perubahan kimia adalah ...',
                'options' => [
                    'A' => 'Es batu mencair menjadi air',
                    'B' => 'Besi dibiarkan di udara terbuka sehingga berkarat',
                    'C' => 'Gula dilarutkan ke dalam air panas',
                    'D' => 'Lilin dipanaskan hingga meleleh',
                    'E' => 'Kawat tembaga dibengkokkan',
                ],
                'key' => 'B',
                'explanation' => "Perubahan kimia menghasilkan zat baru dan umumnya tidak dapat kembali dengan mudah.\n\nBesi berkarat menghasilkan zat baru yaitu besi(III) oksida yang sifatnya berbeda dari besi semula, sehingga termasuk perubahan kimia.\n\nMencair, melarut, meleleh, dan membengkokkan hanya mengubah bentuk atau wujud, jadi termasuk perubahan fisika.",
            ],
            [
                'q' => 'Perubahan wujud dari zat padat langsung menjadi gas disebut ...',
                'options' => [
                    'A' => 'Menguap',
                    'B' => 'Mengembun',
                    'C' => 'Membeku',
                    'D' => 'Menyublim',
                    'E' => 'Mengkristal',
                ],
                'key' => 'D',
                'explanation' => "Menyublim adalah perubahan wujud dari padat langsung menjadi gas tanpa melalui fase cair.\n\nContohnya kapur barus (kamper) yang lama-lama menyusut dan habis karena berubah menjadi gas.",
            ],
            [
                'q' => 'Air garam termasuk ...',
                'options' => [
                    'A' => 'Unsur',
                    'B' => 'Senyawa',
                    'C' => 'Campuran homogen',
                    'D' => 'Campuran heterogen',
                    'E' => 'Zat tunggal',
                ],
                'key' => 'C',
                'explanation' => "Air garam tersusun dari dua zat (air dan garam) yang masih dapat dipisahkan secara fisika, jadi termasuk campuran.\n\nKarena garam larut sempurna sehingga tidak terlihat batas antar zatnya dan rasanya merata, campuran ini bersifat homogen.",
            ],
            [
                'q' => 'Di antara zat berikut yang termasuk unsur adalah ...',
                'options' => [
                    'A' => 'Air (H2O)',
                    'B' => 'Garam dapur (NaCl)',
                    'C' => 'Gas oksigen (O2)',
                    'D' => 'Karbon dioksida (CO2)',
                    'E' => 'Gula (C12H22O11)',
                ],
                'key' => 'C',
                'explanation' => "Unsur hanya tersusun dari satu jenis atom saja.\n\nGas oksigen (O2) hanya terdiri dari atom oksigen, jadi termasuk unsur.\n\nH2O, NaCl, CO2, dan gula tersusun dari dua jenis atom atau lebih, sehingga termasuk senyawa.",
            ],
            [
                'q' => 'Suhu suatu benda 25 derajat Celsius. Jika dinyatakan dalam skala Fahrenheit, suhu tersebut adalah ...',
                'options' => [
                    'A' => '45 derajat F',
                    'B' => '57 derajat F',
                    'C' => '77 derajat F',
                    'D' => '98 derajat F',
                    'E' => '113 derajat F',
                ],
                'key' => 'C',
                'explanation' => "Rumus konversi Celsius ke Fahrenheit:\nF = (9/5 x C) + 32\n\nF = (9/5 x 25) + 32\nF = 45 + 32\nF = 77\n\nJadi 25 derajat C sama dengan 77 derajat F.",
            ],
            [
                'q' => 'Air sebanyak 2 kg dipanaskan sehingga suhunya naik 20 derajat C. Jika kalor jenis air 4.200 J/kg derajat C, kalor yang diperlukan adalah ...',
                'options' => [
                    'A' => '42.000 J',
                    'B' => '84.000 J',
                    'C' => '126.000 J',
                    'D' => '168.000 J',
                    'E' => '210.000 J',
                ],
                'key' => 'D',
                'explanation' => "Gunakan rumus kalor:\nQ = m x c x delta T\n\nQ = 2 kg x 4.200 J/kg derajat C x 20 derajat C\nQ = 168.000 J\n\nJadi kalor yang diperlukan 168.000 J atau 168 kJ.",
            ],
            [
                'q' => 'Sambungan rel kereta api dibuat bercelah. Tujuan pemberian celah tersebut adalah ...',
                'options' => [
                    'A' => 'Memudahkan pemasangan rel',
                    'B' => 'Memberi ruang saat rel memuai ketika suhu naik',
                    'C' => 'Mengurangi berat rel kereta',
                    'D' => 'Menahan getaran roda kereta',
                    'E' => 'Mencegah rel berkarat',
                ],
                'key' => 'B',
                'explanation' => "Logam memuai (bertambah panjang) ketika suhunya naik, misalnya saat terkena panas matahari.\n\nJika rel dipasang rapat tanpa celah, pemuaian akan membuat rel saling mendorong dan melengkung sehingga berbahaya. Celah memberi ruang untuk pemuaian tersebut.",
            ],
            [
                'q' => 'Sebuah mobil menempuh jarak 120 km dalam waktu 2 jam. Kecepatan rata-rata mobil tersebut adalah ...',
                'options' => [
                    'A' => '30 km/jam',
                    'B' => '60 km/jam',
                    'C' => '90 km/jam',
                    'D' => '120 km/jam',
                    'E' => '240 km/jam',
                ],
                'key' => 'B',
                'explanation' => "Kecepatan rata-rata = jarak dibagi waktu.\n\nv = s / t\nv = 120 km / 2 jam\nv = 60 km/jam",
            ],
            [
                'q' => 'Kecepatan 72 km/jam jika diubah ke satuan m/s menjadi ...',
                'options' => [
                    'A' => '10 m/s',
                    'B' => '15 m/s',
                    'C' => '20 m/s',
                    'D' => '25 m/s',
                    'E' => '30 m/s',
                ],
                'key' => 'C',
                'explanation' => "Untuk mengubah km/jam menjadi m/s, bagi dengan 3,6.\n\n72 : 3,6 = 20 m/s\n\nCara lain: 72 km = 72.000 m dan 1 jam = 3.600 s, sehingga 72.000/3.600 = 20 m/s.",
            ],
            [
                'q' => 'Sebuah benda bergerak dari keadaan diam hingga kecepatannya 20 m/s dalam waktu 5 sekon. Percepatan benda tersebut adalah ...',
                'options' => [
                    'A' => '2 m/s kuadrat',
                    'B' => '4 m/s kuadrat',
                    'C' => '5 m/s kuadrat',
                    'D' => '10 m/s kuadrat',
                    'E' => '100 m/s kuadrat',
                ],
                'key' => 'B',
                'explanation' => "Percepatan adalah perubahan kecepatan dibagi waktu.\n\na = (v akhir - v awal) / t\na = (20 - 0) / 5\na = 4 m/s kuadrat",
            ],
            [
                'q' => 'Ketika mobil yang melaju tiba-tiba direm, penumpang terdorong ke depan. Peristiwa ini sesuai dengan ...',
                'options' => [
                    'A' => 'Hukum I Newton tentang kelembaman',
                    'B' => 'Hukum II Newton tentang percepatan',
                    'C' => 'Hukum III Newton tentang aksi-reaksi',
                    'D' => 'Hukum Archimedes',
                    'E' => 'Hukum Pascal',
                ],
                'key' => 'A',
                'explanation' => "Hukum I Newton menyatakan benda cenderung mempertahankan keadaan geraknya. Sifat ini disebut kelembaman atau inersia.\n\nSaat mobil direm, tubuh penumpang masih ingin bergerak maju dengan kecepatan semula, sehingga terasa terdorong ke depan.",
            ],
            [
                'q' => 'Benda bermassa 10 kg didorong sehingga mengalami percepatan 2 m/s kuadrat. Besar gaya yang bekerja pada benda adalah ...',
                'options' => [
                    'A' => '5 N',
                    'B' => '12 N',
                    'C' => '20 N',
                    'D' => '80 N',
                    'E' => '100 N',
                ],
                'key' => 'C',
                'explanation' => "Menurut Hukum II Newton:\nF = m x a\n\nF = 10 kg x 2 m/s kuadrat\nF = 20 N",
            ],
            [
                'q' => 'Gaya sebesar 50 N mendorong sebuah kotak sehingga berpindah 4 meter searah gaya. Usaha yang dilakukan gaya tersebut adalah ...',
                'options' => [
                    'A' => '12,5 J',
                    'B' => '54 J',
                    'C' => '100 J',
                    'D' => '200 J',
                    'E' => '2.000 J',
                ],
                'key' => 'D',
                'explanation' => "Usaha adalah hasil kali gaya dengan perpindahan searah gaya.\n\nW = F x s\nW = 50 N x 4 m\nW = 200 J",
            ],
            [
                'q' => 'Buah bermassa 2 kg berada pada ketinggian 5 meter. Jika percepatan gravitasi 10 m/s kuadrat, energi potensial buah tersebut adalah ...',
                'options' => [
                    'A' => '10 J',
                    'B' => '25 J',
                    'C' => '50 J',
                    'D' => '100 J',
                    'E' => '200 J',
                ],
                'key' => 'D',
                'explanation' => "Energi potensial gravitasi:\nEp = m x g x h\n\nEp = 2 kg x 10 m/s kuadrat x 5 m\nEp = 100 J",
            ],
            [
                'q' => 'Benda bermassa 4 kg bergerak dengan kecepatan 3 m/s. Energi kinetik benda tersebut adalah ...',
                'options' => [
                    'A' => '6 J',
                    'B' => '12 J',
                    'C' => '18 J',
                    'D' => '24 J',
                    'E' => '36 J',
                ],
                'key' => 'C',
                'explanation' => "Energi kinetik:\nEk = 1/2 x m x v kuadrat\n\nEk = 1/2 x 4 x (3 x 3)\nEk = 1/2 x 4 x 9\nEk = 18 J",
            ],
            [
                'q' => 'Keuntungan utama menggunakan bidang miring untuk memindahkan benda berat ke tempat yang lebih tinggi adalah ...',
                'options' => [
                    'A' => 'Usaha yang dilakukan menjadi lebih kecil',
                    'B' => 'Gaya yang diperlukan menjadi lebih kecil',
                    'C' => 'Jarak perpindahan menjadi lebih pendek',
                    'D' => 'Berat benda menjadi berkurang',
                    'E' => 'Waktu yang diperlukan menjadi lebih singkat',
                ],
                'key' => 'B',
                'explanation' => "Bidang miring memperkecil gaya yang diperlukan untuk menaikkan benda, tetapi jarak yang ditempuh menjadi lebih panjang.\n\nUsaha totalnya tetap sama, jadi pesawat sederhana tidak mengurangi usaha, hanya meringankan gaya.",
            ],
            [
                'q' => 'Gaya 200 N bekerja pada bidang seluas 0,5 meter persegi. Tekanan yang dihasilkan adalah ...',
                'options' => [
                    'A' => '100 Pa',
                    'B' => '200 Pa',
                    'C' => '400 Pa',
                    'D' => '1.000 Pa',
                    'E' => '4.000 Pa',
                ],
                'key' => 'C',
                'explanation' => "Tekanan adalah gaya dibagi luas bidang tekan.\n\nP = F / A\nP = 200 N / 0,5 m persegi\nP = 400 N/m persegi = 400 Pa",
            ],
            [
                'q' => 'Seorang penyelam berada pada kedalaman 2 meter di air (massa jenis air 1.000 kg/m kubik, g = 10 m/s kuadrat). Tekanan hidrostatis yang dialaminya adalah ...',
                'options' => [
                    'A' => '200 Pa',
                    'B' => '2.000 Pa',
                    'C' => '5.000 Pa',
                    'D' => '20.000 Pa',
                    'E' => '200.000 Pa',
                ],
                'key' => 'D',
                'explanation' => "Tekanan hidrostatis:\nP = rho x g x h\n\nP = 1.000 kg/m kubik x 10 m/s kuadrat x 2 m\nP = 20.000 Pa",
            ],
            [
                'q' => 'Sebuah benda dimasukkan ke dalam air dan ternyata terapung. Hal ini terjadi karena ...',
                'options' => [
                    'A' => 'Massa benda lebih besar daripada massa air',
                    'B' => 'Massa jenis benda lebih kecil daripada massa jenis air',
                    'C' => 'Massa jenis benda sama dengan massa jenis air',
                    'D' => 'Volume benda lebih besar daripada volume air',
                    'E' => 'Berat benda lebih besar daripada gaya angkat air',
                ],
                'key' => 'B',
                'explanation' => "Menurut Hukum Archimedes, benda terapung jika massa jenis benda lebih kecil daripada massa jenis zat cair.\n\nJika massa jenisnya sama, benda melayang. Jika lebih besar, benda tenggelam.",
            ],
            [
                'q' => 'Alat yang prinsip kerjanya menerapkan Hukum Pascal adalah ...',
                'options' => [
                    'A' => 'Kapal selam',
                    'B' => 'Termometer',
                    'C' => 'Pompa hidrolik pengangkat mobil',
                    'D' => 'Barometer',
                    'E' => 'Balon udara',
                ],
                'key' => 'C',
                'explanation' => "Hukum Pascal menyatakan tekanan pada zat cair dalam ruang tertutup diteruskan sama besar ke segala arah.\n\nPompa hidrolik memanfaatkan prinsip ini: gaya kecil pada penampang sempit menghasilkan gaya besar pada penampang lebar, sehingga mobil dapat terangkat.",
            ],
            [
                'q' => 'Enzim amilase yang terdapat pada air ludah berfungsi mengubah ...',
                'options' => [
                    'A' => 'Protein menjadi asam amino',
                    'B' => 'Amilum menjadi maltosa',
                    'C' => 'Lemak menjadi asam lemak',
                    'D' => 'Maltosa menjadi glukosa',
                    'E' => 'Vitamin menjadi mineral',
                ],
                'key' => 'B',
                'explanation' => "Di dalam mulut terdapat enzim amilase (ptialin) yang bekerja pada karbohidrat.\n\nAmilase mengubah amilum (zat tepung) menjadi maltosa. Itulah sebabnya nasi yang dikunyah lama terasa agak manis.",
            ],
            [
                'q' => 'Penyerapan sari-sari makanan ke dalam pembuluh darah terjadi di ...',
                'options' => [
                    'A' => 'Lambung',
                    'B' => 'Kerongkongan',
                    'C' => 'Usus halus',
                    'D' => 'Usus besar',
                    'E' => 'Rongga mulut',
                ],
                'key' => 'C',
                'explanation' => "Usus halus, khususnya bagian ileum, memiliki jonjot-jonjot usus (vili) yang memperluas permukaan penyerapan.\n\nDi sinilah sari makanan diserap masuk ke pembuluh darah. Usus besar hanya menyerap air dan garam mineral.",
            ],
            [
                'q' => 'Pertukaran gas oksigen dan karbon dioksida pada sistem pernapasan manusia terjadi di ...',
                'options' => [
                    'A' => 'Trakea',
                    'B' => 'Bronkus',
                    'C' => 'Alveolus',
                    'D' => 'Rongga hidung',
                    'E' => 'Laring',
                ],
                'key' => 'C',
                'explanation' => "Alveolus adalah gelembung-gelembung halus di ujung bronkiolus yang dindingnya sangat tipis dan dikelilingi kapiler darah.\n\nStruktur ini memungkinkan oksigen masuk ke darah dan karbon dioksida keluar dari darah secara difusi.",
            ],
            [
                'q' => 'Bagian jantung yang berfungsi memompa darah ke seluruh tubuh adalah ...',
                'options' => [
                    'A' => 'Serambi kanan',
                    'B' => 'Serambi kiri',
                    'C' => 'Bilik kanan',
                    'D' => 'Bilik kiri',
                    'E' => 'Katup jantung',
                ],
                'key' => 'D',
                'explanation' => "Bilik kiri (ventrikel kiri) memompa darah kaya oksigen melalui aorta ke seluruh tubuh.\n\nKarena harus mendorong darah ke jarak yang jauh, dinding bilik kiri paling tebal dan kuat. Bilik kanan hanya memompa darah ke paru-paru.",
            ],
            [
                'q' => 'Zat dalam sel darah merah yang berfungsi mengikat oksigen adalah ...',
                'options' => [
                    'A' => 'Trombosit',
                    'B' => 'Hemoglobin',
                    'C' => 'Plasma darah',
                    'D' => 'Leukosit',
                    'E' => 'Fibrinogen',
                ],
                'key' => 'B',
                'explanation' => "Hemoglobin adalah protein mengandung besi di dalam sel darah merah (eritrosit).\n\nHemoglobin mengikat oksigen di paru-paru dan melepaskannya di jaringan tubuh. Zat inilah yang memberi warna merah pada darah.",
            ],
            [
                'q' => 'Organ ekskresi yang mengeluarkan zat sisa berupa uap air dan karbon dioksida adalah ...',
                'options' => [
                    'A' => 'Ginjal',
                    'B' => 'Kulit',
                    'C' => 'Hati',
                    'D' => 'Paru-paru',
                    'E' => 'Usus besar',
                ],
                'key' => 'D',
                'explanation' => "Sistem ekskresi manusia terdiri dari ginjal (urine), kulit (keringat), hati (urea dan empedu), serta paru-paru.\n\nParu-paru mengeluarkan karbon dioksida dan uap air sebagai hasil sisa pernapasan.",
            ],
            [
                'q' => 'Proses penyaringan darah di dalam ginjal terjadi pada bagian ...',
                'options' => [
                    'A' => 'Glomerulus',
                    'B' => 'Ureter',
                    'C' => 'Kandung kemih',
                    'D' => 'Uretra',
                    'E' => 'Medula',
                ],
                'key' => 'A',
                'explanation' => "Nefron adalah unit penyaring ginjal. Tahap pertama pembentukan urine adalah filtrasi (penyaringan) yang terjadi di glomerulus, di dalam badan Malpighi.\n\nHasil filtrasi disebut urine primer. Ureter, kandung kemih, dan uretra hanya jalur penyaluran dan penampungan urine.",
            ],
            [
                'q' => 'Sebuah benda melakukan 20 getaran dalam waktu 4 sekon. Frekuensi getaran benda tersebut adalah ...',
                'options' => [
                    'A' => '0,2 Hz',
                    'B' => '4 Hz',
                    'C' => '5 Hz',
                    'D' => '16 Hz',
                    'E' => '80 Hz',
                ],
                'key' => 'C',
                'explanation' => "Frekuensi adalah jumlah getaran per sekon.\n\nf = n / t\nf = 20 getaran / 4 s\nf = 5 Hz\n\nPeriodenya T = 1/f = 0,2 sekon.",
            ],
            [
                'q' => 'Gelombang dengan panjang gelombang 0,5 meter dan frekuensi 20 Hz memiliki cepat rambat ...',
                'options' => [
                    'A' => '2,5 m/s',
                    'B' => '10 m/s',
                    'C' => '19,5 m/s',
                    'D' => '40 m/s',
                    'E' => '100 m/s',
                ],
                'key' => 'B',
                'explanation' => "Cepat rambat gelombang:\nv = lambda x f\n\nv = 0,5 m x 20 Hz\nv = 10 m/s",
            ],
            [
                'q' => 'Bunyi tidak dapat merambat di ruang hampa udara karena ...',
                'options' => [
                    'A' => 'Frekuensi bunyi terlalu rendah',
                    'B' => 'Bunyi memerlukan medium untuk merambat',
                    'C' => 'Bunyi merupakan gelombang elektromagnetik',
                    'D' => 'Amplitudo bunyi menjadi nol',
                    'E' => 'Ruang hampa menyerap seluruh bunyi',
                ],
                'key' => 'B',
                'explanation' => "Bunyi adalah gelombang mekanik, artinya perambatannya memerlukan medium berupa zat padat, cair, atau gas.\n\nDi ruang hampa tidak ada partikel medium yang dapat bergetar dan meneruskan bunyi, sehingga bunyi tidak terdengar.",
            ],
            [
                'q' => 'Bunyi yang dapat didengar oleh telinga manusia normal (audiosonik) memiliki rentang frekuensi ...',
                'options' => [
                    'A' => 'Kurang dari 20 Hz',
                    'B' => 'Antara 20 Hz sampai 20.000 Hz',
                    'C' => 'Lebih dari 20.000 Hz',
                    'D' => 'Antara 1 Hz sampai 100 Hz',
                    'E' => 'Tepat 1.000 Hz saja',
                ],
                'key' => 'B',
                'explanation' => "Berdasarkan frekuensinya bunyi dibagi tiga:\n- Infrasonik: kurang dari 20 Hz\n- Audiosonik: 20 Hz sampai 20.000 Hz (dapat didengar manusia)\n- Ultrasonik: lebih dari 20.000 Hz",
            ],
            [
                'q' => 'Sifat bayangan yang dibentuk oleh cermin datar adalah ...',
                'options' => [
                    'A' => 'Nyata, tegak, diperbesar',
                    'B' => 'Nyata, terbalik, sama besar',
                    'C' => 'Maya, tegak, sama besar',
                    'D' => 'Maya, terbalik, diperkecil',
                    'E' => 'Nyata, tegak, diperkecil',
                ],
                'key' => 'C',
                'explanation' => "Cermin datar selalu membentuk bayangan yang maya (di belakang cermin, tidak dapat ditangkap layar), tegak, sama besar dengan bendanya, dan jaraknya sama dengan jarak benda ke cermin.\n\nBayangannya juga tertukar kanan-kiri.",
            ],
            [
                'q' => 'Penderita rabun dekat (hipermetropi) dapat ditolong dengan kacamata berlensa ...',
                'options' => [
                    'A' => 'Cekung (negatif)',
                    'B' => 'Cembung (positif)',
                    'C' => 'Silindris',
                    'D' => 'Datar',
                    'E' => 'Rangkap cekung',
                ],
                'key' => 'B',
                'explanation' => "Hipermetropi adalah kondisi bayangan jatuh di belakang retina sehingga penderita tidak jelas melihat benda dekat.\n\nLensa cembung (positif) bersifat mengumpulkan cahaya sehingga bayangan dapat digeser tepat ke retina.\n\nSebaliknya, miopi (rabun jauh) ditolong dengan lensa cekung (negatif).",
            ],
            [
                'q' => 'Bagian mata yang berfungsi sebagai tempat terbentuknya bayangan adalah ...',
                'options' => [
                    'A' => 'Kornea',
                    'B' => 'Iris',
                    'C' => 'Lensa mata',
                    'D' => 'Retina',
                    'E' => 'Pupil',
                ],
                'key' => 'D',
                'explanation' => "Retina adalah lapisan paling dalam bola mata yang mengandung sel-sel penerima cahaya.\n\nBayangan benda jatuh di retina, lalu rangsangnya dikirim ke otak melalui saraf optik. Pupil hanya mengatur banyak cahaya, dan lensa memfokuskan cahaya.",
            ],
            [
                'q' => 'Penggaris plastik yang digosokkan pada kain wol akan bermuatan negatif karena ...',
                'options' => [
                    'A' => 'Penggaris menerima elektron dari kain wol',
                    'B' => 'Penggaris melepaskan elektron ke kain wol',
                    'C' => 'Penggaris menerima proton dari kain wol',
                    'D' => 'Penggaris melepaskan proton ke kain wol',
                    'E' => 'Penggaris kehilangan neutron',
                ],
                'key' => 'A',
                'explanation' => "Pada penggosokan, yang berpindah hanyalah elektron karena proton dan neutron terikat di inti atom.\n\nPenggaris plastik menarik elektron dari kain wol, sehingga penggaris kelebihan elektron dan bermuatan negatif, sedangkan kain wol menjadi bermuatan positif.",
            ],
            [
                'q' => 'Sebuah lampu dengan hambatan 4 ohm dihubungkan dengan tegangan 12 volt. Kuat arus yang mengalir adalah ...',
                'options' => [
                    'A' => '0,33 A',
                    'B' => '2 A',
                    'C' => '3 A',
                    'D' => '8 A',
                    'E' => '48 A',
                ],
                'key' => 'C',
                'explanation' => "Menurut Hukum Ohm:\nV = I x R, sehingga I = V / R\n\nI = 12 volt / 4 ohm\nI = 3 ampere",
            ],
            [
                'q' => 'Tiga hambatan masing-masing 2 ohm, 3 ohm, dan 5 ohm dirangkai seri. Hambatan totalnya adalah ...',
                'options' => [
                    'A' => '0,97 ohm',
                    'B' => '3,33 ohm',
                    'C' => '5 ohm',
                    'D' => '10 ohm',
                    'E' => '30 ohm',
                ],
                'key' => 'D',
                'explanation' => "Pada rangkaian seri, hambatan total adalah jumlah semua hambatan.\n\nR total = R1 + R2 + R3\nR total = 2 + 3 + 5\nR total = 10 ohm",
            ],
            [
                'q' => 'Dua hambatan 6 ohm dan 3 ohm dirangkai paralel. Hambatan penggantinya adalah ...',
                'options' => [
                    'A' => '2 ohm',
                    'B' => '4,5 ohm',
                    'C' => '9 ohm',
                    'D' => '18 ohm',
                    'E' => '0,5 ohm',
                ],
                'key' => 'A',
                'explanation' => "Pada rangkaian paralel:\n1/Rp = 1/R1 + 1/R2\n\n1/Rp = 1/6 + 1/3 = 1/6 + 2/6 = 3/6\n1/Rp = 1/2\nRp = 2 ohm\n\nHambatan paralel selalu lebih kecil dari hambatan terkecilnya.",
            ],
            [
                'q' => 'Sebuah setrika berdaya 500 watt digunakan selama 2 jam. Energi listrik yang terpakai adalah ...',
                'options' => [
                    'A' => '0,25 kWh',
                    'B' => '1 kWh',
                    'C' => '2 kWh',
                    'D' => '250 kWh',
                    'E' => '1.000 kWh',
                ],
                'key' => 'B',
                'explanation' => "Energi listrik:\nW = P x t\n\nP = 500 watt = 0,5 kilowatt\nW = 0,5 kW x 2 jam\nW = 1 kWh",
            ],
            [
                'q' => 'Jika dua kutub magnet yang sejenis didekatkan, maka akan ...',
                'options' => [
                    'A' => 'Tarik-menarik',
                    'B' => 'Tolak-menolak',
                    'C' => 'Tidak terjadi apa-apa',
                    'D' => 'Kedua magnet kehilangan sifat magnetnya',
                    'E' => 'Berubah menjadi kutub tidak sejenis',
                ],
                'key' => 'B',
                'explanation' => 'Sifat dasar kutub magnet: kutub sejenis (utara dengan utara, atau selatan dengan selatan) tolak-menolak, sedangkan kutub tidak sejenis tarik-menarik.',
            ],
            [
                'q' => 'Cara memperkuat medan magnet pada elektromagnet adalah ...',
                'options' => [
                    'A' => 'Mengurangi jumlah lilitan kawat',
                    'B' => 'Memperkecil kuat arus listrik',
                    'C' => 'Memperbanyak jumlah lilitan dan memperbesar kuat arus',
                    'D' => 'Mengganti inti besi dengan kayu',
                    'E' => 'Memutus aliran listrik secara berkala',
                ],
                'key' => 'C',
                'explanation' => "Kekuatan elektromagnet dapat ditingkatkan dengan tiga cara: memperbesar kuat arus listrik, memperbanyak jumlah lilitan kawat, dan menggunakan inti besi lunak.\n\nKayu bukan bahan magnetik sehingga tidak memperkuat medan magnet.",
            ],
            [
                'q' => 'Planet terbesar dalam sistem tata surya kita adalah ...',
                'options' => [
                    'A' => 'Merkurius',
                    'B' => 'Bumi',
                    'C' => 'Mars',
                    'D' => 'Jupiter',
                    'E' => 'Saturnus',
                ],
                'key' => 'D',
                'explanation' => "Jupiter adalah planet terbesar di tata surya, dengan diameter sekitar 11 kali diameter Bumi.\n\nMerkurius adalah planet terkecil dan paling dekat dengan Matahari, sedangkan Saturnus adalah planet terbesar kedua dan dikenal karena cincinnya.",
            ],
            [
                'q' => 'Pergantian siang dan malam di Bumi terjadi karena ...',
                'options' => [
                    'A' => 'Revolusi Bumi terhadap Matahari',
                    'B' => 'Rotasi Bumi pada porosnya',
                    'C' => 'Revolusi Bulan terhadap Bumi',
                    'D' => 'Kemiringan poros Bumi',
                    'E' => 'Rotasi Matahari pada porosnya',
                ],
                'key' => 'B',
                'explanation' => "Rotasi adalah perputaran Bumi pada porosnya, memerlukan waktu sekitar 24 jam.\n\nBagian Bumi yang menghadap Matahari mengalami siang, sedangkan bagian yang membelakanginya mengalami malam.\n\nRevolusi Bumi (sekitar 365 hari) menyebabkan pergantian musim, bukan siang-malam.",
            ],
            [
                'q' => 'Gerhana bulan terjadi ketika ...',
                'options' => [
                    'A' => 'Bulan berada di antara Matahari dan Bumi',
                    'B' => 'Bumi berada di antara Matahari dan Bulan',
                    'C' => 'Matahari berada di antara Bumi dan Bulan',
                    'D' => 'Bulan dan Bumi berada pada jarak terdekat',
                    'E' => 'Bulan berhenti berevolusi',
                ],
                'key' => 'B',
                'explanation' => "Gerhana bulan terjadi saat posisi Matahari, Bumi, dan Bulan berada pada satu garis dengan Bumi di tengah, sehingga bayangan Bumi menutupi Bulan.\n\nSebaliknya, gerhana matahari terjadi ketika Bulan berada di antara Matahari dan Bumi.",
            ],
            [
                'q' => 'Tanaman berbunga merah bergenotipe Mm disilangkan dengan tanaman sejenis bergenotipe Mm. Jika M (merah) dominan terhadap m (putih), perbandingan fenotipe keturunannya adalah ...',
                'options' => [
                    'A' => 'Merah semua',
                    'B' => 'Putih semua',
                    'C' => '1 merah : 1 putih',
                    'D' => '3 merah : 1 putih',
                    'E' => '1 merah : 3 putih',
                ],
                'key' => 'D',
                'explanation' => "Persilangan Mm x Mm menghasilkan genotipe:\nMM, Mm, mM, mm\n\nGenotipe MM, Mm, dan mM berfenotipe merah (karena M dominan) yaitu 3 bagian, sedangkan mm berfenotipe putih yaitu 1 bagian.\n\nJadi perbandingan fenotipenya 3 merah : 1 putih.",
            ],
            [
                'q' => 'Jumlah kromosom pada sel tubuh manusia normal adalah ...',
                'options' => [
                    'A' => '23 buah',
                    'B' => '23 pasang',
                    'C' => '46 pasang',
                    'D' => '48 buah',
                    'E' => '92 buah',
                ],
                'key' => 'B',
                'explanation' => "Sel tubuh (somatis) manusia memiliki 23 pasang kromosom, yaitu 46 kromosom.\n\nDari jumlah itu, 22 pasang adalah autosom dan 1 pasang adalah kromosom kelamin (XX pada perempuan, XY pada laki-laki).\n\nSel kelamin (sperma dan ovum) hanya memiliki 23 kromosom.",
            ],
            [
                'q' => 'Mikroorganisme yang dimanfaatkan dalam pembuatan tempe adalah ...',
                'options' => [
                    'A' => 'Lactobacillus bulgaricus',
                    'B' => 'Rhizopus oryzae',
                    'C' => 'Saccharomyces cerevisiae',
                    'D' => 'Acetobacter xylinum',
                    'E' => 'Escherichia coli',
                ],
                'key' => 'B',
                'explanation' => "Tempe dibuat dengan bantuan jamur Rhizopus oryzae yang membentuk hifa putih sehingga kedelai menyatu.\n\nLactobacillus bulgaricus dipakai untuk yoghurt, Saccharomyces cerevisiae untuk roti dan tapai, dan Acetobacter xylinum untuk nata de coco.",
            ],
            [
                'q' => 'Kertas lakmus biru yang dimasukkan ke dalam larutan asam akan berubah warna menjadi ...',
                'options' => [
                    'A' => 'Tetap biru',
                    'B' => 'Merah',
                    'C' => 'Hijau',
                    'D' => 'Kuning',
                    'E' => 'Tidak berwarna',
                ],
                'key' => 'B',
                'explanation' => "Sifat larutan dapat diuji dengan kertas lakmus:\n- Larutan asam: lakmus biru menjadi merah, lakmus merah tetap merah\n- Larutan basa: lakmus merah menjadi biru, lakmus biru tetap biru\n- Larutan netral: kedua lakmus tidak berubah",
            ],
            [
                'q' => 'Suatu larutan diukur dengan indikator universal dan menunjukkan pH 4. Larutan tersebut bersifat ...',
                'options' => [
                    'A' => 'Basa kuat',
                    'B' => 'Basa lemah',
                    'C' => 'Netral',
                    'D' => 'Asam',
                    'E' => 'Garam netral',
                ],
                'key' => 'D',
                'explanation' => "Skala pH berkisar 0 sampai 14.\n- pH kurang dari 7: asam\n- pH sama dengan 7: netral\n- pH lebih dari 7: basa\n\nKarena pH = 4 (kurang dari 7), larutan tersebut bersifat asam.",
            ],
            [
                'q' => 'Bahan berikut yang merupakan pengawet alami untuk makanan adalah ...',
                'options' => [
                    'A' => 'Natrium benzoat',
                    'B' => 'Garam dapur',
                    'C' => 'Boraks',
                    'D' => 'Formalin',
                    'E' => 'Rhodamin B',
                ],
                'key' => 'B',
                'explanation' => "Garam dapur dan gula adalah pengawet alami karena menarik air dari sel mikroorganisme sehingga bakteri tidak dapat berkembang. Cara ini dipakai pada ikan asin dan manisan.\n\nNatrium benzoat adalah pengawet sintetis yang masih diizinkan, sedangkan boraks, formalin, dan Rhodamin B dilarang untuk makanan karena berbahaya.",
            ],
            [
                'q' => 'Dalam suatu ekosistem sawah, yang berperan sebagai produsen adalah ...',
                'options' => [
                    'A' => 'Padi',
                    'B' => 'Belalang',
                    'C' => 'Katak',
                    'D' => 'Ular',
                    'E' => 'Jamur',
                ],
                'key' => 'A',
                'explanation' => "Produsen adalah makhluk hidup yang mampu membuat makanan sendiri melalui fotosintesis, yaitu tumbuhan hijau.\n\nPadi adalah tumbuhan hijau sehingga berperan sebagai produsen. Belalang, katak, dan ular adalah konsumen, sedangkan jamur berperan sebagai pengurai (dekomposer).",
            ],
            [
                'q' => 'Perhatikan rantai makanan berikut: padi -> belalang -> katak -> ular. Jika populasi katak menurun drastis, yang paling mungkin terjadi adalah ...',
                'options' => [
                    'A' => 'Populasi belalang meningkat dan populasi ular menurun',
                    'B' => 'Populasi belalang menurun dan populasi ular meningkat',
                    'C' => 'Populasi padi dan ular sama-sama meningkat',
                    'D' => 'Semua populasi meningkat',
                    'E' => 'Tidak ada perubahan pada populasi lain',
                ],
                'key' => 'A',
                'explanation' => "Katak adalah pemakan belalang sekaligus makanan bagi ular.\n\nJika katak berkurang, belalang kehilangan pemangsa sehingga populasinya meningkat, dan akibatnya padi banyak dimakan. Di sisi lain ular kehilangan sumber makanan sehingga populasinya menurun.",
            ],
            [
                'q' => 'Makhluk hidup yang berperan sebagai pengurai (dekomposer) dalam ekosistem adalah ...',
                'options' => [
                    'A' => 'Tumbuhan hijau',
                    'B' => 'Hewan herbivora',
                    'C' => 'Hewan karnivora',
                    'D' => 'Bakteri dan jamur',
                    'E' => 'Hewan omnivora',
                ],
                'key' => 'D',
                'explanation' => "Dekomposer menguraikan sisa-sisa makhluk hidup yang telah mati menjadi zat hara sederhana yang dapat digunakan kembali oleh tumbuhan.\n\nPeran ini dijalankan oleh bakteri dan jamur, sehingga daur materi dalam ekosistem tetap berjalan.",
            ],
            [
                'q' => 'Penggunaan pupuk buatan yang berlebihan di sawah dapat menyebabkan pencemaran air berupa ...',
                'options' => [
                    'A' => 'Hujan asam',
                    'B' => 'Eutrofikasi, yaitu ledakan pertumbuhan tumbuhan air',
                    'C' => 'Efek rumah kaca',
                    'D' => 'Lubang pada lapisan ozon',
                    'E' => 'Kenaikan suhu udara global',
                ],
                'key' => 'B',
                'explanation' => "Sisa pupuk yang terbawa ke perairan menambah zat hara secara berlebihan. Akibatnya tumbuhan air seperti alga dan ganggang tumbuh sangat cepat. Peristiwa ini disebut eutrofikasi.\n\nTumbuhan yang mati kemudian diuraikan bakteri sehingga oksigen dalam air berkurang dan ikan dapat mati.",
            ],
            [
                'q' => 'Untuk mengukur volume batu kecil yang bentuknya tidak teratur, alat yang paling tepat digunakan adalah ...',
                'options' => [
                    'A' => 'Neraca ohaus',
                    'B' => 'Jangka sorong',
                    'C' => 'Gelas ukur berisi air',
                    'D' => 'Termometer',
                    'E' => 'Mikrometer sekrup',
                ],
                'key' => 'C',
                'explanation' => "Volume benda tidak teratur diukur dengan cara memasukkannya ke gelas ukur berisi air, lalu menghitung selisih tinggi air sebelum dan sesudah batu dimasukkan.\n\nSelisih volume air itulah volume batu. Neraca mengukur massa, sedangkan jangka sorong dan mikrometer hanya cocok untuk benda beraturan.",
            ],
            [
                'q' => 'Fotosintesis pada tumbuhan hijau menghasilkan ...',
                'options' => [
                    'A' => 'Karbon dioksida dan air',
                    'B' => 'Glukosa dan oksigen',
                    'C' => 'Oksigen dan karbon dioksida',
                    'D' => 'Air dan mineral',
                    'E' => 'Klorofil dan energi panas',
                ],
                'key' => 'B',
                'explanation' => "Reaksi fotosintesis dapat ditulis:\n6 CO2 + 6 H2O + cahaya -> C6H12O6 + 6 O2\n\nBahan yang dibutuhkan adalah karbon dioksida dan air, sedangkan hasilnya adalah glukosa (bahan makanan) dan oksigen yang dilepaskan ke udara.\n\nKlorofil bukan hasil, melainkan zat hijau daun yang berperan menyerap cahaya.",
            ],
        ];
    }
}
